# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8abac835ac993971ec4cd27a48a977288760bba73843aa113a563c3543b737721f66305eab8696679ebb48f678bfca8eff162911b460cf7505c2b620c82bd2

test:
  secret_key_base: fd87374e19cf74906523da4e298f285d87152fbc9a72c4dba14eb52bdef1de4263a080230c0a527ac8c18510b10b55720dfe31b9eeb0ec588a7e12581a92dc5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
